### PR TITLE
Adding the done clause to the loop

### PR DESCRIPTION
**Pull request by vinhali**
It should come after the done at the end of your while loop.

Error: `/ticketz-scripts/envtojson.sh: line 7: syntax error: unexpected end of file (expecting "done")`

### CODE REVIEW

**Comment by erickythierry** [comment]
I tried using this solution but it still gives the same error

**Comment by allgood** [comment]
this is a problem with the conversion of the file by git. 

When cloning the repository you should use the command that is on the README;

git -c core.autocrlf=input clone https://github.com/ticketz-oss/ticketz.git


The `core.autocrlf=input` parameter makes sure that the file will not be converted by git.

**Comment by erickythierry** [comment]
I made a modification to make it work because I couldn't use it.

in the `/frontend/scripts/envtojson.sh` file
I changed it to this:

```
#!/bin/bash

python -c 'import json, os;print(json.dumps(dict(os.environ)))'
```

and in the `/frontend/dockerfile` I added this line
`RUN apk update && apk add python3`
on line 25

This way it worked for the purpose of the script

**Comment by allgood** [comment]
Thank you @erickythierry , I am avoiding the use of external commands and installations on the container. I am fixing this bug dealing with the conversion inside the Dockerfile

**Pull request closed without merging**
